# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-28 22:51
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=None, verbose_name='Date Generated')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Admin Changelog Entries',
                'verbose_name': 'Admin Changelog Entry',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, default=None, max_length=16, null=True, verbose_name='Phone Number')),
                ('max_num_patients', models.IntegerField(default=20, verbose_name='Maximum Number of Patients')),
            ],
            options={
                'verbose_name': 'Doctor',
            },
            bases=('auth.user',),
            managers=[
                ('manager', django.contrib.auth.models.UserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Hospital Name')),
                ('max_num_patients', models.IntegerField(default=1000, verbose_name='Maximum Number of Patients')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalAdmin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, default=None, max_length=14, null=True, verbose_name='Phone Number')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins_list', to='users.Hospital')),
            ],
            options={
                'verbose_name': 'Hospital Admin',
            },
            bases=('auth.user',),
            managers=[
                ('manager', django.contrib.auth.models.UserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, default=None, max_length=14, null=True, verbose_name='Phone Number')),
                ('doctors_list', models.ManyToManyField(related_name='nurses_list', to='users.Doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurses_list', to='users.Hospital')),
            ],
            options={
                'verbose_name': 'Nurse',
            },
            bases=('auth.user',),
            managers=[
                ('manager', django.contrib.auth.models.UserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('I', 'Intersex')], max_length=1, verbose_name='Biological Sex')),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name='Gender')),
                ('birthdate', models.DateField(verbose_name='Date of Birth')),
                ('insurance_num', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{1}[a-zA-Z0-9]{11}', 'Must match insurance number format.')], verbose_name='Insurance Number')),
                ('phone', models.CharField(blank=True, default=None, max_length=16, null=True, verbose_name='Phone Number')),
                ('address', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Address')),
                ('e_first_name', models.CharField(blank=True, default=' ', max_length=20, verbose_name="Contact's First Name")),
                ('e_last_name', models.CharField(blank=True, default=' ', max_length=20, verbose_name="Contact's Last Name")),
                ('e_phone', models.CharField(blank=True, default=' ', max_length=15, verbose_name="Contact's Phone Number")),
                ('dr', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='patients_list', to='users.Doctor', verbose_name='Doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_list', to='users.Hospital')),
            ],
            options={
                'verbose_name': 'Patient',
            },
            bases=('auth.user',),
            managers=[
                ('manager', django.contrib.auth.models.UserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospitals_list',
            field=models.ManyToManyField(blank=True, default=None, related_name='doctors_list', to='users.Hospital'),
        ),
        migrations.AddField(
            model_name='changelogentry',
            name='generatedby',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Generated By'),
        ),
        migrations.AddField(
            model_name='changelogentry',
            name='hospital',
            field=models.ForeignKey(default=None, on_delete=users.models.Hospital, to='users.Hospital'),
        ),
    ]
