# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-02 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161029_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admitted',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admitted_list', to='users.Hospital'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, verbose_name='Phone Number'),
        ),
    ]
