# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-07 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161102_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admitted_dr',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admitted_patient_list', to='users.Doctor'),
        ),
    ]
