# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-05 21:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_patient_admitted_dr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance_num',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{1}[a-zA-Z0-9]{12}', 'Must match insurance number format.')], verbose_name='Insurance Number'),
        ),
    ]
