# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-02 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0002_auto_20161028_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(default=30, help_text='in minutes', verbose_name='Duration of appointment'),
        ),
    ]
