# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-28 22:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EMR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Electronic Medical Record',
            },
        ),
        migrations.CreateModel(
            name='EMRItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('is_released_to_patient', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'EMR Item',
            },
        ),
        migrations.CreateModel(
            name='ChangeInStatus',
            fields=[
                ('emritem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emr.EMRItem')),
                ('reason', models.CharField(choices=[('SUR', 'Surgery'), ('EMER', 'Emergency'), ('OBS', 'Observation'), ('OTH', 'Other')], max_length=150, verbose_name='Reason')),
            ],
            bases=('emr.emritem',),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('emritem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emr.EMRItem')),
                ('message', models.CharField(max_length=500, verbose_name='Message')),
            ],
            bases=('emr.emritem',),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('emritem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emr.EMRItem')),
                ('name', models.CharField(max_length=150, verbose_name='Prescription name')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('dosage', models.IntegerField(default=5, verbose_name='Dosage')),
                ('units', models.CharField(default='mg', help_text='Please use abbreviations', max_length=5, verbose_name='Units of dosage')),
            ],
            bases=('emr.emritem',),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('emritem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emr.EMRItem')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('result', models.CharField(max_length=500, verbose_name='Result')),
                ('comments', models.CharField(blank=True, max_length=500, verbose_name='Comments')),
                ('image', models.FileField(blank=True, upload_to='/media/', verbose_name='Optional image')),
            ],
            bases=('emr.emritem',),
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('emritem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emr.EMRItem')),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Height')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Weight')),
                ('blood_pressure_str', models.CharField(blank=True, max_length=7, null=True, verbose_name='Blood Pressure')),
                ('cholesterol', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Cholesterol')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='Heart rate')),
            ],
            options={
                'verbose_name_plural': 'Vitals',
            },
            bases=('emr.emritem',),
        ),
        migrations.AddField(
            model_name='emritem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emritem',
            name='emr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emritems_list', to='emr.EMR'),
        ),
    ]
