# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-28 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emr', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emr',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emr', to='users.Patient'),
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('changeinstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emr.ChangeInStatus')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors_list', to='users.Doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions_list', to='users.Hospital')),
            ],
            bases=('emr.changeinstatus',),
        ),
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('changeinstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emr.ChangeInStatus')),
            ],
            bases=('emr.changeinstatus',),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('changeinstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emr.ChangeInStatus')),
                ('receiving_hospital', models.CharField(default=0, max_length=100, verbose_name='Hospital')),
                ('receiving_doctor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_list', to='users.Doctor')),
            ],
            bases=('emr.changeinstatus',),
        ),
    ]
