# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-04 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161102_2133'),
        ('emr', '0002_auto_20161028_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='hospital',
        ),
        migrations.AddField(
            model_name='changeinstatus',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_change_list', to='users.Doctor'),
        ),
        migrations.AddField(
            model_name='changeinstatus',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_change_list', to='users.Hospital'),
        ),
    ]
