# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-07 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0004_auto_20161105_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='receiving_hospital',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_list', to='users.Hospital'),
        ),
    ]
